//Volem mostrejar totes les categories disponibles de llibres amb el Webscraper i amb la CutreWay
//This version has no CutreWay!!!

var categoriesNames=[
    "Travel"
    ,"Mystery"
    ,"Historical Fiction"
    ,"Sequential Art"
    ,"Classics"
    ,"Philosophy"
    ,"Romance"
    ,"Womens Fiction"
    ,"Fiction"
    ,"Childrens"
    ,"Religion"
    ,"Nonfiction"
    ,"Music"
    ,"Default"
    ,"Science Fiction"
    ,"Sports and Games"
    ,"Add a comment"
    ,"Fantasy"
    ,"New Adult"
    ,"Young Adult"
    ,"Science"
    ,"Poetry"
    ,"Paranormal"
    ,"Art"
    ,"Psychology"
    ,"Autobiography"
    ,"Parenting"
    ,"Adult Fiction"
    ,"Humor"
    ,"Horror"
    ,"History"
    ,"Food and Drink"
    ,"Christian Fiction"
    ,"Business"
    ,"Biography"
    ,"Thriller"
    ,"Contemporary"
    ,"Spirituality"
    ,"Academic"
    ,"Self Help"
    ,"Historical"
    ,"Christian"
    ,"Suspense"
    ,"Short Stories"
    ,"Novels"
    ,"Health"
    ,"Politics"
    ,"Cultural"
    ,"Erotica"
    ,"Crime"];

    exports.categoriesNames = categoriesNames;

